<a href="https://colab.research.google.com/github/jaissonjpp/image_processing/blob/main/image_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from io import BytesIO
from PIL import Image
import numpy as np

In [ ]:
image_data = open('/content/photo.jpeg', 'rb').read()
img = Image.open(BytesIO(image_data))

In [ ]:

print(img.size)
print(img.format)

(3000, 1929)
JPEG


In [ ]:
img_array = np.array(img)

In [ ]:
img_array.shape

(1929, 3000, 3)

In [ ]:
img_array.dtype

dtype('uint8')

In [ ]:
print(img_array.min())
print(img_array.max())

0
255


In [ ]:
print(img_array.mean())
print(img_array.std())

153.69955359714302
68.27518883906332


In [ ]:
print(img_array[0][0])

[ 72 143 185]


In [ ]:
img_red = np.zeros_like(img_array)
img_green = np.zeros_like(img_array)
img_blue = np.zeros_like(img_array)
img_red[:, :, 0] = img_array[:, :, 0]
img_green[:, :, 1] = img_array[:, :, 1]
img_blue[:, :, 2] = img_array[:, :, 2]

In [ ]:
print(img_red[0][0])
print(img_green[0][0])
print(img_blue[0][0])

[72  0  0]
[  0 143   0]
[  0   0 185]


In [ ]:
img_red = Image.fromarray(img_red.astype(np.uint8))
img_green = Image.fromarray(img_green.astype(np.uint8))
img_blue = Image.fromarray(img_blue.astype(np.uint8))

In [ ]:
img_red.save("red_image.jpg")
img_green.save("green_image.jpg")
img_blue.save("blue_image.jpg")

In [ ]:
import numpy as np

# Carregue as imagens como arrays NumPy (substitua pelos seus nomes de arquivo)
img1 = np.array(Image.open('/content/photo1.jpeg'))
img2 = np.array(Image.open('/content/red_image.jpg'))

# Defina o fator de interpolação (alpha)
alpha = 0.5

# Interpole as imagens
interpolated_image = img1 * alpha + img2 * (1 - alpha)

# Converta a imagem interpolada de volta para o tipo uint8
interpolated_image = interpolated_image.astype(np.uint8)

# Salve a imagem interpolada (substitua pelo nome de arquivo desejado)
Image.fromarray(interpolated_image).save('interpolated_image_red.jpg')

In [ ]:
import numpy as np

# Carregue as imagens como arrays NumPy
img1 = np.array(Image.open('interpolated_image_red.jpg'))
img2 = np.array(Image.open('photo1.jpeg'))

# Calcule a diferença quadrada entre as imagens
squared_diff = (img1 - img2) ** 2

# Calcule a média da diferença quadrada
mse = np.mean(squared_diff)

# Imprima o resultado
print("MSE:", mse)

MSE: 76.34324364955935
